import { type WaitlistEntry, type Table } from './supabase'

// Mock Waitlist Data
export const mockWaitlist: Record<string, WaitlistEntry[]> = {
  '1/3': [
    {
      id: '1',
      store_id: 'store-1',
      user_id: 'user-1',
      user_name: 'John Chen',
      rate_preference: '1/3',
      status: 'waiting',
      called_at: null,
      arrival_estimation_minutes: 15,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '2',
      store_id: 'store-1',
      user_id: 'user-2',
      user_name: 'Sarah Lin',
      rate_preference: '1/3',
      status: 'called',
      called_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
      arrival_estimation_minutes: 30,
      created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '3',
      store_id: 'store-1',
      user_id: 'user-3',
      user_name: 'Mike Wang',
      rate_preference: '1/3',
      status: 'waiting',
      called_at: null,
      arrival_estimation_minutes: null,
      created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '4',
      store_id: 'store-1',
      user_id: 'user-4',
      user_name: 'Lisa Huang',
      rate_preference: '1/3',
      status: 'called',
      called_at: new Date(Date.now() - 11 * 60 * 1000).toISOString(), // 11 minutes ago (will blink)
      arrival_estimation_minutes: 20,
      created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  '2/5': [
    {
      id: '5',
      store_id: 'store-1',
      user_id: 'user-5',
      user_name: 'David Lee',
      rate_preference: '2/5',
      status: 'waiting',
      called_at: null,
      arrival_estimation_minutes: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '6',
      store_id: 'store-1',
      user_id: 'user-6',
      user_name: 'Emma Wu',
      rate_preference: '2/5',
      status: 'waiting',
      called_at: null,
      arrival_estimation_minutes: 25,
      created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  '5/10+': [
    {
      id: '7',
      store_id: 'store-1',
      user_id: 'user-7',
      user_name: 'Kevin Zhang',
      rate_preference: '5/10+',
      status: 'waiting',
      called_at: null,
      arrival_estimation_minutes: null,
      created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  'Tournament': [],
}

// Mock Tables Data
export const mockTables: Record<string, Table[]> = {
  '1/3': [
    {
      id: 'table-1',
      store_id: 'store-1',
      rate: '1/3',
      max_seats: 9,
      current_players: 8,
      status: 'open',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'table-2',
      store_id: 'store-1',
      rate: '1/3',
      max_seats: 9,
      current_players: 7,
      status: 'open',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'table-3',
      store_id: 'store-1',
      rate: '1/3',
      max_seats: 9,
      current_players: 9,
      status: 'open',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  '2/5': [
    {
      id: 'table-4',
      store_id: 'store-1',
      rate: '2/5',
      max_seats: 9,
      current_players: 6,
      status: 'open',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'table-5',
      store_id: 'store-1',
      rate: '2/5',
      max_seats: 9,
      current_players: 8,
      status: 'open',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  '5/10+': [
    {
      id: 'table-6',
      store_id: 'store-1',
      rate: '5/10+',
      max_seats: 9,
      current_players: 5,
      status: 'open',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  'Tournament': [],
}
